- name: Deploy Flask App
  hosts: localhost
  tasks:
    - name: Stop existing app (if running)
      shell: pkill -f app.py || true
      ignore_errors: yes

    - name: Run Flask app in background
      shell: nohup ./venv/bin/python3 app.py &
